// SPDX-License-Identifier: MIT OR Apache-2.0

//! DSM namespace tags: device-birth binding

/// Domain tag for the deterministic device-birth attestation digest `AttA`:
/// `AttA = BLAKE3(TAG || LP(nonce_commitment) || LP(creation_mode) || ...)`.
/// Folded into the per-device key derivation (whitepaper §11.1) in place of the
/// removed silicon anti-clone binding.  Install/device-lineage binding only — NOT an
/// anti-clone proof.
pub const TAG_DSM_DEVICE_BIRTH_ATT: &str = "DSM/device-birth-att/v1";

/// Domain tag for the device-birth nonce commitment:
/// `commitment = BLAKE3(TAG || birth_nonce)`, where `birth_nonce` is 32 fresh
/// CSPRNG bytes generated by the SDK at genesis.  The commitment (not the
/// nonce) is persisted and folded VERBATIM into `AttA`, so finalize/restore
/// re-derive an identical `AttA`.  Rust owns this end-to-end — the host never
/// computes or supplies it (rules.instructions.md: Rust is the sole crypto
/// authority; Kotlin is transport-only).
pub const TAG_DSM_DEVICE_BIRTH_NONCE: &str = "DSM/device-birth-nonce/v1";

/// Domain tag for the soft-vault at-rest device binding key (storage-encryption
/// only; not a protocol identity).  `key = BLAKE3(TAG || device_id_hint)`.
pub const TAG_DSM_SOFT_VAULT_BINDING: &str = "DSM/soft-vault-binding/v1";
