//! The on-device appliance wire protocol, generated by prost from the in-crate
//! `proto/dsm_anchor.proto` schema. Conversion helpers between the wire messages
//! and the anchor-core domain types live alongside the generated module.
//!
//! All fixed-width fields (32-byte ids/hashes) are validated on decode here,
//! since the schema carries them as plain `bytes`; opaque fields are bounded.

extern crate alloc;
use alloc::vec::Vec;

use prost::Message;

use crate::boot::BootTicket;
use crate::root_advance::{
    Certificate, CounterAdvanceEvidence, CounterReadEvidence, OfflineRelease, OwnedTransition,
};

/// prost-generated message types (package `dsm.anchor`).
#[allow(clippy::all, clippy::pedantic, missing_docs)]
pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/dsm.anchor.rs"));
}

/// Wire-decode / conversion failures.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ProtoError {
    /// A fixed-width (32-byte) field had the wrong length, or a bounded opaque
    /// field exceeded its cap.
    BadLength,
    /// A required sub-message was absent.
    MissingField,
    /// An unknown or unspecified op selector.
    BadOp,
    /// A `slot` value outside `u16`.
    BadSlot,
    /// prost failed to decode the frame bytes.
    Decode,
}

/// Upper bound on the opaque `action_fields` (a small structured tagged-union).
pub const MAX_ACTION_FIELDS: usize = 256;
/// Upper bound on each DSM SMT leaf proof (depth ≤ 256 × 32 B + framing).
pub const MAX_LEAF_PROOF: usize = 16 * 1024;
/// Upper bound on a revealed witness/partition public key.
pub const MAX_PK: usize = 4 * 1024;
/// Upper bound on a signature (WOTS σ is 2144 B; SPHINCS+ partition σ is tens of KiB).
pub const MAX_SIGMA: usize = 128 * 1024;
/// Upper bound on the authenticated L3 counter-read transcript.
pub const MAX_TRANSCRIPT: usize = 8 * 1024;
/// Upper bound on the boot chain length (boots since the committed boot head).
pub const MAX_BOOT_CHAIN: usize = 256;

/// Validate a 32-byte field.
pub fn arr32(v: &[u8]) -> Result<[u8; 32], ProtoError> {
    if v.len() != 32 {
        return Err(ProtoError::BadLength);
    }
    let mut a = [0u8; 32];
    a.copy_from_slice(v);
    Ok(a)
}

fn bounded(v: &[u8], cap: usize) -> Result<(), ProtoError> {
    if v.len() > cap {
        Err(ProtoError::BadLength)
    } else {
        Ok(())
    }
}

// --- TransitionPackage <-> OwnedTransition (Δ) ---

impl pb::TransitionPackage {
    pub fn to_owned_transition(&self) -> Result<OwnedTransition, ProtoError> {
        bounded(&self.action_fields, MAX_ACTION_FIELDS)?;
        bounded(&self.old_leaf_proof, MAX_LEAF_PROOF)?;
        bounded(&self.new_leaf_proof, MAX_LEAF_PROOF)?;
        Ok(OwnedTransition {
            relationship_id: arr32(&self.relationship_id)?,
            object_id: arr32(&self.object_id)?,
            sender_device_id: arr32(&self.sender_device_id)?,
            recipient_device_id: arr32(&self.recipient_device_id)?,
            prev_root: arr32(&self.prev_root)?,
            next_root: arr32(&self.next_root)?,
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            action_type: self.action_type,
            action_fields: self.action_fields.clone(),
            payload_hash: arr32(&self.payload_hash)?,
            old_leaf_proof: self.old_leaf_proof.clone(),
            new_leaf_proof: self.new_leaf_proof.clone(),
            authority_policy_hash: arr32(&self.authority_policy_hash)?,
        })
    }
}

impl OwnedTransition {
    pub fn to_pb(&self) -> pb::TransitionPackage {
        pb::TransitionPackage {
            relationship_id: self.relationship_id.to_vec(),
            object_id: self.object_id.to_vec(),
            sender_device_id: self.sender_device_id.to_vec(),
            recipient_device_id: self.recipient_device_id.to_vec(),
            prev_root: self.prev_root.to_vec(),
            next_root: self.next_root.to_vec(),
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            action_type: self.action_type,
            action_fields: self.action_fields.clone(),
            payload_hash: self.payload_hash.to_vec(),
            old_leaf_proof: self.old_leaf_proof.clone(),
            new_leaf_proof: self.new_leaf_proof.clone(),
            authority_policy_hash: self.authority_policy_hash.to_vec(),
        }
    }
}

// --- BootTicket <-> BootTicket ---

impl pb::BootTicket {
    pub fn to_ticket(&self) -> Result<BootTicket, ProtoError> {
        bounded(&self.partition_boot_signature, MAX_SIGMA)?;
        Ok(BootTicket {
            anchor_bundle: arr32(&self.anchor_bundle)?,
            anchor_head: arr32(&self.anchor_head)?,
            prev_boot_head: arr32(&self.prev_boot_head)?,
            next_boot_head: arr32(&self.next_boot_head)?,
            boot_seq: self.boot_seq,
            firmware_measurement: arr32(&self.firmware_measurement)?,
            partition_boot_signature: self.partition_boot_signature.clone(),
            tropic_boot_input: arr32(&self.tropic_boot_input)?,
            tropic_boot_witness: arr32(&self.tropic_boot_witness)?,
        })
    }
}

impl BootTicket {
    pub fn to_pb(&self) -> pb::BootTicket {
        pb::BootTicket {
            anchor_bundle: self.anchor_bundle.to_vec(),
            anchor_head: self.anchor_head.to_vec(),
            prev_boot_head: self.prev_boot_head.to_vec(),
            next_boot_head: self.next_boot_head.to_vec(),
            boot_seq: self.boot_seq,
            firmware_measurement: self.firmware_measurement.to_vec(),
            partition_boot_signature: self.partition_boot_signature.clone(),
            tropic_boot_input: self.tropic_boot_input.to_vec(),
            tropic_boot_witness: self.tropic_boot_witness.to_vec(),
        }
    }
}

// --- RootAdvanceCertificate <-> Certificate ---

impl pb::RootAdvanceCertificate {
    pub fn to_cert(&self) -> Result<Certificate, ProtoError> {
        bounded(&self.pk_hw, MAX_PK)?;
        bounded(&self.sigma_tropic, MAX_SIGMA)?;
        bounded(&self.sigma_partition, MAX_SIGMA)?;
        let transfer_slot = u16::try_from(self.transfer_slot).map_err(|_| ProtoError::BadSlot)?;
        Ok(Certificate {
            anchor_bundle: arr32(&self.anchor_bundle)?,
            prev_anchor_head: arr32(&self.prev_anchor_head)?,
            next_anchor_head: arr32(&self.next_anchor_head)?,
            prev_boot_head: arr32(&self.prev_boot_head)?,
            current_boot_head: arr32(&self.current_boot_head)?,
            prev_root: arr32(&self.prev_root)?,
            next_root: arr32(&self.next_root)?,
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            transition_digest: arr32(&self.transition_digest)?,
            root_advance_message: arr32(&self.root_advance_message)?,
            partition_commitment: arr32(&self.partition_commitment)?,
            tropic_transfer_input: arr32(&self.tropic_transfer_input)?,
            pk_hash: arr32(&self.pk_hash)?,
            pk_hw: self.pk_hw.clone(),
            sigma_tropic: self.sigma_tropic.clone(),
            sigma_partition: self.sigma_partition.clone(),
            anchor_id: arr32(&self.anchor_id)?,
            transfer_slot,
            receiver_challenge: arr32(&self.receiver_challenge)?,
        })
    }
}

impl Certificate {
    pub fn to_pb(&self) -> pb::RootAdvanceCertificate {
        pb::RootAdvanceCertificate {
            anchor_bundle: self.anchor_bundle.to_vec(),
            prev_anchor_head: self.prev_anchor_head.to_vec(),
            next_anchor_head: self.next_anchor_head.to_vec(),
            prev_boot_head: self.prev_boot_head.to_vec(),
            current_boot_head: self.current_boot_head.to_vec(),
            prev_root: self.prev_root.to_vec(),
            next_root: self.next_root.to_vec(),
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            transition_digest: self.transition_digest.to_vec(),
            root_advance_message: self.root_advance_message.to_vec(),
            partition_commitment: self.partition_commitment.to_vec(),
            tropic_transfer_input: self.tropic_transfer_input.to_vec(),
            pk_hash: self.pk_hash.to_vec(),
            pk_hw: self.pk_hw.clone(),
            sigma_tropic: self.sigma_tropic.clone(),
            sigma_partition: self.sigma_partition.clone(),
            anchor_id: self.anchor_id.to_vec(),
            transfer_slot: self.transfer_slot as u32,
            receiver_challenge: self.receiver_challenge.to_vec(),
        }
    }
}

// --- CounterReadEvidence / CounterAdvanceEvidence <-> pb ---

impl pb::CounterReadEvidence {
    pub fn to_read(&self) -> Result<CounterReadEvidence, ProtoError> {
        bounded(&self.verifier_transcript, MAX_TRANSCRIPT)?;
        Ok(CounterReadEvidence {
            anchor_id: arr32(&self.anchor_id)?,
            attested_raw_counter: self.attested_raw_counter,
            verifier_transcript: self.verifier_transcript.clone(),
            binding_hash: arr32(&self.binding_hash)?,
        })
    }
}

impl CounterReadEvidence {
    pub fn to_pb(&self) -> pb::CounterReadEvidence {
        pb::CounterReadEvidence {
            anchor_id: self.anchor_id.to_vec(),
            attested_raw_counter: self.attested_raw_counter,
            verifier_transcript: self.verifier_transcript.clone(),
            binding_hash: self.binding_hash.to_vec(),
        }
    }
}

impl pb::CounterAdvanceEvidence {
    pub fn to_evidence(&self) -> Result<CounterAdvanceEvidence, ProtoError> {
        Ok(CounterAdvanceEvidence {
            pre: self
                .pre
                .as_ref()
                .ok_or(ProtoError::MissingField)?
                .to_read()?,
            post: self
                .post
                .as_ref()
                .ok_or(ProtoError::MissingField)?
                .to_read()?,
            binding_hash: arr32(&self.binding_hash)?,
        })
    }
}

impl CounterAdvanceEvidence {
    pub fn to_pb(&self) -> pb::CounterAdvanceEvidence {
        pb::CounterAdvanceEvidence {
            pre: Some(self.pre.to_pb()),
            post: Some(self.post.to_pb()),
            binding_hash: self.binding_hash.to_vec(),
        }
    }
}

// --- OfflineRelease <-> OfflineRelease ---

impl pb::OfflineRelease {
    pub fn to_release(&self) -> Result<OfflineRelease, ProtoError> {
        if self.boot_chain.len() > MAX_BOOT_CHAIN {
            return Err(ProtoError::BadLength);
        }
        let transition = self
            .transition
            .as_ref()
            .ok_or(ProtoError::MissingField)?
            .to_owned_transition()?;
        let mut boot_chain = Vec::with_capacity(self.boot_chain.len());
        for t in &self.boot_chain {
            boot_chain.push(t.to_ticket()?);
        }
        let cert = self
            .cert
            .as_ref()
            .ok_or(ProtoError::MissingField)?
            .to_cert()?;
        let counter = self
            .counter
            .as_ref()
            .ok_or(ProtoError::MissingField)?
            .to_evidence()?;
        Ok(OfflineRelease {
            transition,
            boot_chain,
            cert,
            counter,
        })
    }
}

impl OfflineRelease {
    pub fn to_pb(&self) -> pb::OfflineRelease {
        pb::OfflineRelease {
            transition: Some(self.transition.to_pb()),
            boot_chain: self.boot_chain.iter().map(|t| t.to_pb()).collect(),
            cert: Some(self.cert.to_pb()),
            counter: Some(self.counter.to_pb()),
        }
    }
}

// --- Frame codec (prost Message encode/decode) ---

/// Decode an `ApplianceRequest` frame (firmware/secure-core side).
pub fn decode_request(bytes: &[u8]) -> Result<pb::ApplianceRequest, ProtoError> {
    pb::ApplianceRequest::decode(bytes).map_err(|_| ProtoError::Decode)
}

/// Encode an `ApplianceResponse` (firmware/secure-core side).
pub fn encode_response(resp: &pb::ApplianceResponse) -> Vec<u8> {
    resp.encode_to_vec()
}

/// Encode an `ApplianceRequest` (host/transport side).
pub fn encode_request(req: &pb::ApplianceRequest) -> Vec<u8> {
    req.encode_to_vec()
}

/// Encode an `OfflineRelease` sub-message to its canonical bytes — what a USB appliance client puts
/// into `BilateralConfirmRequest.offline_release` after reading it from an `EMIT` response.
pub fn encode_release(rel: &pb::OfflineRelease) -> Vec<u8> {
    rel.encode_to_vec()
}

/// Decode an `ApplianceResponse` frame (host/transport side).
pub fn decode_response(bytes: &[u8]) -> Result<pb::ApplianceResponse, ProtoError> {
    pb::ApplianceResponse::decode(bytes).map_err(|_| ProtoError::Decode)
}
