//! The on-device appliance wire protocol, generated by prost from the in-crate
//! `proto/dsm_anchor.proto` schema (v2). Conversion helpers between the wire messages
//! and the anchor-core domain types live alongside the generated module.
//!
//! All fixed-width fields (32-byte ids/hashes) are validated on decode here, since the
//! schema carries them as plain `bytes`; opaque fields are bounded.

extern crate alloc;
use alloc::vec::Vec;

use prost::Message;

use crate::root_advance::{Certificate, OfflineRelease, OwnedTransition};

/// prost-generated message types (package `dsm.anchor`).
#[allow(clippy::all, clippy::pedantic, missing_docs)]
pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/dsm.anchor.rs"));
}

/// Wire-decode / conversion failures.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ProtoError {
    /// A fixed-width (32-byte) field had the wrong length, or a bounded opaque field
    /// exceeded its cap.
    BadLength,
    /// A required sub-message was absent.
    MissingField,
    /// An unknown or unspecified op selector.
    BadOp,
    /// prost failed to decode the frame bytes.
    Decode,
}

/// Upper bound on the opaque `action_fields` (a small structured tagged-union).
pub const MAX_ACTION_FIELDS: usize = 256;
/// Upper bound on each DSM SMT leaf / inclusion proof (depth ≤ 256 × 32 B + framing).
pub const MAX_LEAF_PROOF: usize = 16 * 1024;
/// Upper bound on a signature (Ed25519 σ^chip is 64 B; SPHINCS+ σ^host is tens of KiB).
pub const MAX_SIGMA: usize = 128 * 1024;
/// Upper bound on the branch-proof length (prior certs for frontier catch-up).
pub const MAX_BRANCH_PROOF: usize = 256;

/// Validate a 32-byte field.
pub fn arr32(v: &[u8]) -> Result<[u8; 32], ProtoError> {
    if v.len() != 32 {
        return Err(ProtoError::BadLength);
    }
    let mut a = [0u8; 32];
    a.copy_from_slice(v);
    Ok(a)
}

fn bounded(v: &[u8], cap: usize) -> Result<(), ProtoError> {
    if v.len() > cap {
        Err(ProtoError::BadLength)
    } else {
        Ok(())
    }
}

// --- TransitionPackage <-> OwnedTransition (Δ) ---

impl pb::TransitionPackage {
    pub fn to_owned_transition(&self) -> Result<OwnedTransition, ProtoError> {
        bounded(&self.action_fields, MAX_ACTION_FIELDS)?;
        bounded(&self.old_leaf_proof, MAX_LEAF_PROOF)?;
        bounded(&self.new_leaf_proof, MAX_LEAF_PROOF)?;
        Ok(OwnedTransition {
            relationship_id: arr32(&self.relationship_id)?,
            object_id: arr32(&self.object_id)?,
            sender_device_id: arr32(&self.sender_device_id)?,
            recipient_device_id: arr32(&self.recipient_device_id)?,
            prev_root: arr32(&self.prev_root)?,
            next_root: arr32(&self.next_root)?,
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            action_type: self.action_type,
            action_fields: self.action_fields.clone(),
            payload_hash: arr32(&self.payload_hash)?,
            old_leaf_proof: self.old_leaf_proof.clone(),
            new_leaf_proof: self.new_leaf_proof.clone(),
            authority_policy_hash: arr32(&self.authority_policy_hash)?,
        })
    }
}

impl OwnedTransition {
    pub fn to_pb(&self) -> pb::TransitionPackage {
        pb::TransitionPackage {
            relationship_id: self.relationship_id.to_vec(),
            object_id: self.object_id.to_vec(),
            sender_device_id: self.sender_device_id.to_vec(),
            recipient_device_id: self.recipient_device_id.to_vec(),
            prev_root: self.prev_root.to_vec(),
            next_root: self.next_root.to_vec(),
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            action_type: self.action_type,
            action_fields: self.action_fields.clone(),
            payload_hash: self.payload_hash.to_vec(),
            old_leaf_proof: self.old_leaf_proof.clone(),
            new_leaf_proof: self.new_leaf_proof.clone(),
            authority_policy_hash: self.authority_policy_hash.to_vec(),
        }
    }
}

// --- RootAdvanceCertificate <-> Certificate (v2 three-signature) ---

impl pb::RootAdvanceCertificate {
    pub fn to_cert(&self) -> Result<Certificate, ProtoError> {
        bounded(&self.sigma_chip, MAX_SIGMA)?;
        bounded(&self.sigma_host, MAX_SIGMA)?;
        Ok(Certificate {
            anchor_bundle: arr32(&self.anchor_bundle)?,
            sender_device_root_before: arr32(&self.sender_device_root_before)?,
            sender_device_root_after: arr32(&self.sender_device_root_after)?,
            prev_frontier: arr32(&self.prev_frontier)?,
            next_frontier: arr32(&self.next_frontier)?,
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            transition_digest: arr32(&self.transition_digest)?,
            root_advance_message: arr32(&self.root_advance_message)?,
            anchor_id: arr32(&self.anchor_id)?,
            sigma_chip: self.sigma_chip.clone(),
            sigma_host: self.sigma_host.clone(),
            receiver_challenge: arr32(&self.receiver_challenge)?,
            recipient: arr32(&self.recipient)?,
        })
    }
}

impl Certificate {
    pub fn to_pb(&self) -> pb::RootAdvanceCertificate {
        pb::RootAdvanceCertificate {
            anchor_bundle: self.anchor_bundle.to_vec(),
            sender_device_root_before: self.sender_device_root_before.to_vec(),
            sender_device_root_after: self.sender_device_root_after.to_vec(),
            prev_frontier: self.prev_frontier.to_vec(),
            next_frontier: self.next_frontier.to_vec(),
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            transition_digest: self.transition_digest.to_vec(),
            root_advance_message: self.root_advance_message.to_vec(),
            anchor_id: self.anchor_id.to_vec(),
            sigma_chip: self.sigma_chip.clone(),
            sigma_host: self.sigma_host.clone(),
            receiver_challenge: self.receiver_challenge.to_vec(),
            recipient: self.recipient.to_vec(),
        }
    }
}

// --- OfflineRelease <-> OfflineRelease ---

impl pb::OfflineRelease {
    pub fn to_release(&self) -> Result<OfflineRelease, ProtoError> {
        bounded(&self.anchor_smt_proof_before, MAX_LEAF_PROOF)?;
        bounded(&self.anchor_smt_proof_after, MAX_LEAF_PROOF)?;
        if self.branch_proof.len() > MAX_BRANCH_PROOF {
            return Err(ProtoError::BadLength);
        }
        let transition = self
            .transition
            .as_ref()
            .ok_or(ProtoError::MissingField)?
            .to_owned_transition()?;
        let cert = self.cert.as_ref().ok_or(ProtoError::MissingField)?.to_cert()?;
        let mut branch_proof = Vec::with_capacity(self.branch_proof.len());
        for c in &self.branch_proof {
            branch_proof.push(c.to_cert()?);
        }
        Ok(OfflineRelease {
            transition,
            anchor_smt_proof_before: self.anchor_smt_proof_before.clone(),
            anchor_smt_proof_after: self.anchor_smt_proof_after.clone(),
            cert,
            branch_proof,
        })
    }
}

impl OfflineRelease {
    pub fn to_pb(&self) -> pb::OfflineRelease {
        pb::OfflineRelease {
            transition: Some(self.transition.to_pb()),
            anchor_smt_proof_before: self.anchor_smt_proof_before.clone(),
            anchor_smt_proof_after: self.anchor_smt_proof_after.clone(),
            cert: Some(self.cert.to_pb()),
            branch_proof: self.branch_proof.iter().map(|c| c.to_pb()).collect(),
        }
    }
}

// --- Frame codec (prost Message encode/decode) ---

/// Decode an `ApplianceRequest` frame (firmware/secure-core side).
pub fn decode_request(bytes: &[u8]) -> Result<pb::ApplianceRequest, ProtoError> {
    pb::ApplianceRequest::decode(bytes).map_err(|_| ProtoError::Decode)
}

/// Encode an `ApplianceResponse` (firmware/secure-core side).
pub fn encode_response(resp: &pb::ApplianceResponse) -> Vec<u8> {
    resp.encode_to_vec()
}

/// Encode an `ApplianceRequest` (host/transport side).
pub fn encode_request(req: &pb::ApplianceRequest) -> Vec<u8> {
    req.encode_to_vec()
}

/// Encode an `OfflineRelease` sub-message to its canonical bytes — what a USB appliance
/// client puts into `BilateralConfirmRequest.offline_release` after reading it from an
/// `EMIT` response.
pub fn encode_release(rel: &pb::OfflineRelease) -> Vec<u8> {
    rel.encode_to_vec()
}

/// Decode an `ApplianceResponse` frame (host/transport side).
pub fn decode_response(bytes: &[u8]) -> Result<pb::ApplianceResponse, ProtoError> {
    pb::ApplianceResponse::decode(bytes).map_err(|_| ProtoError::Decode)
}
