#!/bin/bash

# Build script for protobuf code generation across Rust and Android
set -e

echo "🔧 Building protobuf definitions..."

# Build Rust protobuf code
echo "📦 Building Rust protobuf code..."
cd dsm_client/deterministic_state_machine/dsm
# Proto code is generated by build scripts (dsm_sdk) from the single source of truth:
#   /proto/dsm_app.proto
# There is no standalone `proto` feature on the `dsm` crate; generation happens when building `dsm_sdk`.
cargo build -p dsm_sdk --locked
cd - > /dev/null

# Android generates its own bindings: app/build.gradle.kts applies the protobuf
# Gradle plugin to ../../../proto, and every Gradle build compiles it into the
# build directory. Nothing to do here.
echo "📱 Android protobuf code: generated by the Android Gradle build (protobuf plugin)"

echo "✅ Protobuf code generation completed!"
echo ""
echo "Generated files:"
echo "  - Rust: target/*/build/*/out/ (via prost and tonic-build, OUT_DIR)"
echo "  - TypeScript: dsm_client/frontend/src/proto/dsm_app_pb.ts (via npm run proto:gen)"
echo "  - Android: dsm_client/android/app/build/ (via the Gradle protobuf plugin)"
