version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/dsm_client/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "frontend"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"
