// SPDX-License-Identifier: Apache-2.0
//
// The guided tour, step by step. Each step names the real screen it runs on,
// the real element it points at, and, for hands-on steps, what the user has to
// do before the tour moves on. Everything the user does runs in practice mode:
// the bridge lets only reads through, so the steps that show what a write does
// (creating a token, trading, the lock, a ring backup) walk through the real
// screen with that write switched off.

import type { ScreenType } from '../../types/app';
import type { PracticeEvent } from './practiceMode';
import { PRACTICE_CONTACT_CODE } from './practiceContact';

export type TourWait =
  /** Move on once this screen is open. */
  | { kind: 'screen'; screen: ScreenType }
  /** Move on once this element is on screen. */
  | { kind: 'selector'; selector: string }
  /** Move on once nothing on screen matches this selector any more. */
  | { kind: 'gone'; selector: string }
  /** Move on once this field holds a value (a positive number when `positive`). */
  | { kind: 'value'; selector: string; positive?: boolean }
  /** Move on once practice mode reports this action. */
  | { kind: 'event'; event: PracticeEvent };

export type TourStep = {
  id: string;
  /** The screen this step runs on. The tour opens it if it is not already open. */
  screen: ScreenType;
  /** CSS selector of the element the step points at. No target: the guide just talks. */
  target?: string;
  title: string;
  body: string;
  /** Hands-on steps: what the user must do. The tour moves on by itself. */
  wait?: TourWait;
  /** Short instruction shown in place of NEXT on hands-on steps. */
  prompt?: string;
  /** A home menu brick to highlight, so pressing A opens it. */
  menuItem?: string;
  /** Clicking an element matching this selector means the user backed out: go back one step. */
  backOn?: string;
  /** Text the user needs on this step, such as a code to paste: shown selectable, with a button that copies it. */
  copy?: { label: string; text: string };
};

export const TOUR_STEPS: ReadonlyArray<TourStep> = [
  {
    id: 'welcome',
    screen: 'home',
    title: 'Welcome to StateBoy',
    body: "I'm your guide. I'll take you through every screen and point at each thing as we go. You'll try things for real, in practice mode: nothing you do in this tour touches your wallet.",
  },
  {
    id: 'button-a',
    screen: 'home',
    target: '#button-a',
    title: 'This is A',
    body: 'A picks whatever is highlighted. Press it now to keep going.',
  },
  {
    id: 'button-b',
    screen: 'home',
    target: '#button-b',
    title: 'This is B',
    body: 'B steps back: out of a screen, or back one step in this tour. Tap NEXT to carry on.',
  },
  {
    id: 'dpad',
    screen: 'home',
    target: '.new-dpad, #dpad-up',
    title: 'The D-pad',
    body: 'The D-pad moves the highlight through a menu. You can always tap the screen instead.',
  },
  {
    id: 'start-select',
    screen: 'home',
    target: '#button-start',
    title: 'START and SELECT',
    body: 'START turns sound on and off. SELECT, right beside it, changes the color theme. Long-press SELECT to change the shell itself: gold, zebra, leopard and more.',
  },
  {
    id: 'menu',
    screen: 'home',
    target: '.dsm-menu[aria-label="Main Menu"]',
    title: 'The main menu',
    body: 'Every part of the wallet starts from here.',
  },
  {
    id: 'go-wallet',
    screen: 'home',
    target: '.dsm-menu-item[data-label="WALLET"]',
    menuItem: 'WALLET',
    title: 'Your turn',
    body: "Tap WALLET to open your wallet. Pressing A works too, because it's highlighted.",
    wait: { kind: 'screen', screen: 'wallet' },
    prompt: 'Tap WALLET',
  },
  {
    id: 'balances',
    screen: 'wallet',
    target: '[aria-label="Your balances"]',
    title: 'Your balances',
    body: 'Every token you hold shows here. These are practice numbers: 1000 ERA and 50 PLAY to play with.',
  },
  {
    id: 'wallet-tabs',
    screen: 'wallet',
    target: '.sb-tabs[aria-label="Wallet sections"]',
    title: 'Wallet tabs',
    body: 'These tabs switch the wallet between its overview, sending, and your history. Swapping lives on the TRADE screen.',
  },
  {
    id: 'go-send',
    screen: 'wallet',
    target: '.overview-tab .sb-actions .sb-btn--primary',
    title: "Let's send something",
    body: "Tap Send. We'll pay some practice tokens to alice, a practice contact.",
    wait: { kind: 'selector', selector: '.send-tab' },
    prompt: 'Tap Send',
  },
  {
    id: 'ticker',
    screen: 'wallet',
    target: '.send-tab > .sb-card',
    title: 'Your token ticker',
    body: "Do you see this? That short name is the token's ticker, the quickest way to know which token you're dealing with. The number beside it is how much of it you hold.",
  },
  {
    id: 'info',
    screen: 'wallet',
    target: '.send-tab [aria-label="About sending modes"]',
    title: 'Stuck? Look for i',
    body: 'Tap an i on any screen for a plain explanation of what is there.',
  },
  {
    id: 'recipient',
    screen: 'wallet',
    target: '#recipient',
    title: 'Who gets it',
    body: "Pick who you're paying. Choose alice from the list.",
    wait: { kind: 'value', selector: '#recipient' },
    prompt: 'Pick alice',
  },
  {
    id: 'recipient-check',
    screen: 'wallet',
    target: '[data-testid="send-recipient-confirm"]',
    title: 'Check who',
    body: "Did you notice that line? It spells out the device you're paying. A name can be anything; this is who it really goes to.",
  },
  {
    id: 'amount',
    screen: 'wallet',
    target: '#amount',
    title: 'How much',
    body: 'Now go ahead and enter an amount. Try 25.',
    wait: { kind: 'value', selector: '#amount', positive: true },
    prompt: 'Type an amount',
  },
  {
    id: 'token',
    screen: 'wallet',
    target: '.send-tab .sb-tokensel--inline',
    title: 'Which token',
    body: "This is the token it'll be paid in. When you hold more than one, make sure this ticker is the one you mean.",
  },
  {
    id: 'double-check',
    screen: 'wallet',
    target: '.send-tab .sb-input-row',
    title: 'Stop and look',
    body: "Before you hit Send, check the amount and the token together. You'll be asked to confirm, but pay attention now: once it's sent, there is no undo.",
  },
  {
    id: 'press-send',
    screen: 'wallet',
    target: '.send-tab button[type="submit"]',
    title: 'Send it',
    body: 'Happy with it? Tap Send.',
    wait: { kind: 'selector', selector: '.bilateral-transfer-dialog' },
    prompt: 'Tap Send',
  },
  {
    id: 'confirm',
    screen: 'wallet',
    target: '.bilateral-transfer-dialog',
    title: 'Last look',
    body: 'This is your last chance to back out. Read it once more: the amount, the token, and who. Then tap Confirm.',
    wait: { kind: 'event', event: 'sent' },
    prompt: 'Tap Confirm',
    backOn: '.bilateral-btn-reject',
  },
  {
    id: 'sent',
    screen: 'wallet',
    target: '[aria-label="Your balances"]',
    title: 'Sent',
    body: "Done. Your practice balance went down by exactly what you sent. For real, it would now be waiting in alice's inbox, even if her phone is off.",
  },
  {
    id: 'recent-activity',
    screen: 'wallet',
    target: '[data-tour="recent-activity"]',
    title: 'Recent activity',
    body: 'Your latest payments, newest first. Tap one to open it: its memo, who it was from and to, and its receipt.',
  },
  {
    id: 'wallet-identity',
    screen: 'wallet',
    target: '.wallet-identity',
    title: 'Who this wallet is',
    body: "Wallet identity holds this wallet's genesis and this device's id. Open it when someone needs to check it is really you.",
  },
  {
    id: 'go-history',
    screen: 'wallet',
    target: '.sb-tabs[aria-label="Wallet sections"] button:nth-of-type(3)',
    title: 'Your history',
    body: 'Open History.',
    wait: { kind: 'selector', selector: '.history-tab' },
    prompt: 'Tap History',
  },
  {
    id: 'history',
    screen: 'wallet',
    target: '.history-tab',
    title: 'Everything, in order',
    body: 'Every payment, faucet claim, token you made and trade you did, newest first, each with a badge saying what it was. Tap one for its details.',
  },
  {
    id: 'go-inbox',
    screen: 'wallet',
    target: 'button[aria-label^="Inbox"]',
    title: 'Your inbox',
    body: 'Payments sent to you online wait on your storage nodes until this phone picks them up. Tap Inbox.',
    wait: { kind: 'selector', selector: '[role="dialog"][aria-label="Inbox"]' },
    prompt: 'Tap Inbox',
  },
  {
    id: 'inbox',
    screen: 'wallet',
    target: '[role="dialog"][aria-label="Inbox"]',
    title: 'What came in',
    body: 'This is your real inbox, only read. Recently applied is what this phone has already counted. Queued on storage node is still waiting to be picked up; it lands on its own.',
  },
  {
    id: 'close-inbox',
    screen: 'wallet',
    target: '[aria-label="Close inbox"]',
    title: 'Close it',
    body: 'Close the inbox.',
    wait: { kind: 'gone', selector: '[role="dialog"][aria-label="Inbox"]' },
    prompt: 'Tap ×',
  },
  {
    id: 'go-tokens',
    screen: 'home',
    target: '.dsm-menu-item[data-label="TOKENS"]',
    menuItem: 'TOKENS',
    title: 'Tokens',
    body: "Let's look at your tokens. Tap TOKENS.",
    wait: { kind: 'screen', screen: 'accounts' },
    prompt: 'Tap TOKENS',
  },
  {
    id: 'token-tabs',
    screen: 'accounts',
    target: '[data-tour="tokens-tabs"]',
    title: 'Balances and Faucet',
    body: 'Balances lists every token on this wallet. Faucet hands out free ERA so you can try things.',
  },
  {
    id: 'create-token',
    screen: 'accounts',
    target: '[data-tour="create-token"]',
    title: 'Your own token',
    body: 'Create Token makes a token of your own, under rules you set when you make it. Tap it to look inside.',
    wait: { kind: 'selector', selector: '.token-wizard' },
    prompt: 'Tap Create Token',
  },
  {
    id: 'token-wizard',
    screen: 'accounts',
    target: '.token-wizard',
    title: 'Three pages',
    body: 'Identity: its ticker, name, decimals and coin. Supply: the whole amount that will ever exist, whether holders may burn it, and who may hold it. Review: the creation fee, paid in ERA and burned. None of it can change afterwards. In practice, Create is switched off.',
  },
  {
    id: 'close-wizard',
    screen: 'accounts',
    target: '.token-wizard .sb-popover__close',
    title: 'Close it',
    body: "We won't make one now. Close it.",
    wait: { kind: 'gone', selector: '.token-wizard' },
    prompt: 'Tap ×',
  },
  {
    id: 'add-token',
    screen: 'accounts',
    target: '[data-tour="add-token"]',
    title: "Someone else's token",
    body: "Add Token takes the policy anchor a token's creator shares, and learns its rules so this wallet can hold it. Nothing is issued and no fee is paid.",
  },
  {
    id: 'go-faucet',
    screen: 'accounts',
    target: '[data-tour="tokens-tabs"] button:nth-of-type(2)',
    title: 'Free tokens',
    body: 'Open the Faucet tab.',
    wait: { kind: 'selector', selector: '[data-tour="faucet-claim"]' },
    prompt: 'Tap Faucet',
  },
  {
    id: 'claim',
    screen: 'accounts',
    target: '[data-tour="faucet-claim"]',
    title: 'Claim some',
    body: "Tap Claim Faucet. In practice you'll get 100 ERA straight away.",
    wait: { kind: 'event', event: 'claimed' },
    prompt: 'Tap Claim Faucet',
  },
  {
    id: 'claimed',
    screen: 'accounts',
    target: '[data-tour="tokens-tabs"]',
    title: 'There they are',
    body: 'Your practice ERA just went up by 100. Balances shows every token you hold, any time.',
  },
  {
    id: 'go-balances',
    screen: 'accounts',
    target: '[data-tour="tokens-tabs"] button:nth-of-type(1)',
    title: 'Back to Balances',
    body: 'Open Balances again.',
    wait: { kind: 'selector', selector: '.tokens-tab' },
    prompt: 'Tap Balances',
  },
  {
    id: 'token-row',
    screen: 'accounts',
    target: '.tokens-tab .token-card',
    title: 'Open a token',
    body: 'Each token is a card. Tap one to open it.',
    wait: { kind: 'selector', selector: '.token-card.is-open' },
    prompt: 'Tap a token',
  },
  {
    id: 'token-detail',
    screen: 'accounts',
    target: '.token-card.is-open .sb-card--dark',
    title: 'What a token is',
    body: 'Its supply, its decimals and who defined it: the rules it was made with, and nobody can change them.',
  },
  {
    id: 'token-actions',
    screen: 'accounts',
    target: '.token-card.is-open',
    title: 'Burn and Forget',
    body: "A token someone created shows more here. Burn destroys some of what you hold, when its rules allow it. Forget stops listing it; adding it again brings it back. ERA is the protocol's own, so it has neither. In practice, both are switched off.",
  },
  {
    id: 'token-share',
    screen: 'accounts',
    target: '.token-card.is-open',
    title: 'Sharing a token',
    body: "A created token's card also shows its policy anchor, with Copy Anchor, and a QR that others scan to add it. A token travels by its anchor, never by its name.",
  },
  {
    id: 'go-trade',
    screen: 'home',
    target: '.dsm-menu-item[data-label="TRADE"]',
    menuItem: 'TRADE',
    title: 'Trade',
    body: 'Now the market. Tap TRADE.',
    wait: { kind: 'screen', screen: 'sofi' },
    prompt: 'Tap TRADE',
  },
  {
    id: 'trade-tabs',
    screen: 'sofi',
    target: '.sb-tabs[aria-label="SoFi sections"]',
    title: 'Sovereign liquidity',
    body: 'This is SoFi: sovereign finance. Swap trades one token for another. Liquidity is where that comes from: vaults that people like you put up. No exchange sits in the middle; it settles between devices.',
  },
  {
    id: 'swap-pay',
    screen: 'sofi',
    target: '[data-tour="swap-pay"]',
    title: 'What you pay',
    body: 'Type how much you pay and pick the token. Only a token that carries a policy anchor can trade, so in practice this list is empty.',
  },
  {
    id: 'swap-get',
    screen: 'sofi',
    target: '[data-tour="swap-get"]',
    title: 'What you get',
    body: "Pick the token you want, or paste its policy anchor if you don't hold it yet.",
  },
  {
    id: 'trade-quote',
    screen: 'sofi',
    target: '.swap-tab .sb-btn--primary.sb-btn--block',
    title: 'Quote, then trade',
    body: "Quote finds a route through people's vaults and shows its hops, what you'd get, and the least you'll accept. Trade then lands at a position, or is void if someone else's trade won the race, and then nothing moved. In practice, Trade is switched off.",
  },
  {
    id: 'go-liquidity',
    screen: 'sofi',
    target: '.sb-tabs[aria-label="SoFi sections"] button:nth-of-type(2)',
    title: 'Liquidity',
    body: 'Open the Liquidity tab.',
    wait: { kind: 'selector', selector: '.liquidity-tab' },
    prompt: 'Tap Liquidity',
  },
  {
    id: 'liquidity-vault',
    screen: 'sofi',
    target: '[data-tour="liquidity-create"]',
    title: 'Your own liquidity vault',
    body: 'Pick two of your tokens and how much of each to put in: their amounts set the price. The fee, in basis points, is what every trade against your vault pays you. In practice, Create is switched off.',
  },
  {
    id: 'liquidity-close',
    screen: 'sofi',
    target: '[data-tour="liquidity-close"]',
    title: 'Closing a vault',
    body: 'Close takes a vault of yours by its id and gives both reserves back to you. Storage lists your vaults, with their live reserves, under DLVs.',
  },
  {
    id: 'liquidity-relay',
    screen: 'sofi',
    target: '.sofi-relay',
    title: 'Relaying',
    body: "If someone's trade was registered but never finished, anyone can complete it here with their genesis, device id and position. You will rarely need it.",
  },
  {
    id: 'resolve',
    screen: 'sofi',
    target: '.sofi-screen .sb-screen__actions .sb-btn',
    title: 'Resolve',
    body: 'If a trade was cut short, Resolve finishes what this phone still has pending. You will rarely need it.',
  },
  {
    id: 'go-contacts',
    screen: 'home',
    target: '.dsm-menu-item[data-label="CONTACTS"]',
    menuItem: 'CONTACTS',
    title: 'Contacts',
    body: 'Next, the people you deal with. Tap CONTACTS.',
    wait: { kind: 'screen', screen: 'contacts' },
    prompt: 'Tap CONTACTS',
  },
  {
    id: 'contact-tabs',
    screen: 'contacts',
    target: '[data-tour="contacts-tabs"]',
    title: 'Your contacts',
    body: "My Contacts lists everyone you've added. Add Contact takes someone's code to add them. My QR shows your own code, so others can add you.",
  },
  {
    id: 'go-add-contact',
    screen: 'contacts',
    target: '[data-tour="contacts-tabs"] button:nth-of-type(2)',
    title: 'Add someone',
    body: "Let's add a practice contact, bob. Open Add Contact.",
    wait: { kind: 'selector', selector: '[data-tour="contact-code"]' },
    prompt: 'Tap Add Contact',
  },
  {
    id: 'paste-code',
    screen: 'contacts',
    target: '[data-tour="contact-code"]',
    title: "Bob's code",
    body: "Normally you'd scan their QR, or paste a code they sent you. Here is bob's: copy it, paste it into the box, then tap Use Contact Code.",
    copy: { label: 'Copy', text: PRACTICE_CONTACT_CODE },
    wait: { kind: 'selector', selector: '.qr-scanner [role="dialog"]' },
    prompt: 'Paste it, then Use Contact Code',
  },
  {
    id: 'add-bob',
    screen: 'contacts',
    target: '.qr-scanner [role="dialog"]',
    title: 'Contact found',
    body: "Your wallet read the code: this is bob's device and genesis. What you add is his device; the name is only your label for him. Tap Add.",
    wait: { kind: 'event', event: 'contactAdded' },
    prompt: 'Tap Add',
  },
  {
    id: 'go-my-contacts',
    screen: 'contacts',
    target: '[data-tour="contacts-tabs"] button:nth-of-type(1)',
    title: 'There he is',
    body: 'Open My Contacts.',
    wait: { kind: 'selector', selector: '[data-tour="contact-list"]' },
    prompt: 'Tap My Contacts',
  },
  {
    id: 'open-contact',
    screen: 'contacts',
    target: '[data-tour="contact-list"]',
    title: 'Open a contact',
    body: 'Tap a contact to open it.',
    wait: { kind: 'selector', selector: '[data-tour="contact-list"] .sb-row__detail' },
    prompt: 'Tap a contact',
  },
  {
    id: 'contact-detail',
    screen: 'contacts',
    target: '[data-tour="contact-list"] .sb-row__detail',
    title: 'Who they are',
    body: "Their device, their genesis, the tip of your chain with them, and their key: what every payment between you is checked against. Stitched receipts are the payments you've exchanged, each with its proof.",
  },
  {
    id: 'go-my-qr',
    screen: 'contacts',
    target: '[data-tour="contacts-tabs"] button:nth-of-type(3)',
    title: 'Your code',
    body: 'Open My QR.',
    wait: { kind: 'selector', selector: '.my-contact' },
    prompt: 'Tap My QR',
  },
  {
    id: 'my-qr',
    screen: 'contacts',
    target: '.my-contact .sb-card--hero',
    title: 'This is you',
    body: "Someone scans this once and you're in their contacts. Every payment they send you after that goes to this device, whatever they call you.",
  },
  {
    id: 'contact-code',
    screen: 'contacts',
    target: '[aria-label="Copy contact code"]',
    title: "Can't scan?",
    body: 'Copy the code and send it any way you like. It says the same thing as the picture.',
  },
  {
    id: 'go-storage',
    screen: 'home',
    target: '.dsm-menu-item[data-label="STORAGE"]',
    menuItem: 'STORAGE',
    title: 'Storage',
    body: 'Tap STORAGE.',
    wait: { kind: 'screen', screen: 'storage' },
    prompt: 'Tap STORAGE',
  },
  {
    id: 'storage',
    screen: 'storage',
    target: '.sb-tabs[aria-label="Storage sections"]',
    title: 'Storage nodes',
    body: "Storage nodes keep copies of what you publish, so people can reach you while you're offline. They hold bytes and decide nothing. Three tabs: your set, each node in it, and your vaults.",
  },
  {
    id: 'storage-set',
    screen: 'storage',
    target: '[aria-label="Storage set status"]',
    title: 'Your set',
    body: 'Answered is how many of your nodes replied just now. Syncs counts the times this phone caught up with them. Local DB is what this phone keeps of its own.',
  },
  {
    id: 'go-members',
    screen: 'storage',
    target: '.sb-tabs[aria-label="Storage sections"] button:nth-of-type(2)',
    title: 'The nodes',
    body: 'Open Members.',
    wait: { kind: 'selector', selector: '[aria-label="Storage members"]' },
    prompt: 'Tap Members',
  },
  {
    id: 'members',
    screen: 'storage',
    target: '[aria-label="Storage members"]',
    title: 'Each node',
    body: 'One row per node, with a dot for whether it answered. Tap a row for what it holds of yours. A quiet node is only quiet: nodes keep bytes and decide nothing.',
  },
  {
    id: 'go-dlvs',
    screen: 'storage',
    target: '.sb-tabs[aria-label="Storage sections"] button:nth-of-type(3)',
    title: 'Your vaults',
    body: 'Open DLVs.',
    wait: { kind: 'selector', selector: '[data-tour="liquidity-vaults"]' },
    prompt: 'Tap DLVs',
  },
  {
    id: 'dlvs',
    screen: 'storage',
    target: '[data-tour="liquidity-vaults"]',
    title: 'Liquidity vaults',
    body: "The vaults you've put up for trading, read from your storage nodes, each with its live reserves. This is your real list: practice makes no vaults.",
  },
  {
    id: 'go-settings',
    screen: 'home',
    target: '.dsm-menu-item[data-label="SETTINGS"]',
    menuItem: 'SETTINGS',
    title: 'Settings',
    body: 'Last stop. Tap SETTINGS.',
    wait: { kind: 'screen', screen: 'settings' },
    prompt: 'Tap SETTINGS',
  },
  {
    id: 'version',
    screen: 'settings',
    target: '.settings-screen button.sb-card',
    title: 'Developer options',
    body: 'Tap the version seven times and Developer Options appears: policy tools, for tokens you build yourself.',
  },
  {
    id: 'security',
    screen: 'settings',
    target: '[aria-labelledby="security-section-title"]',
    title: 'Lock it',
    body: "Lock the wallet with a PIN or a combo of the shell's buttons, so nobody else can open it.",
  },
  {
    id: 'go-lock',
    screen: 'settings',
    target: '[aria-labelledby="security-section-title"] .sb-btn--primary',
    title: 'Setting the lock',
    body: 'Tap Configure wallet lock.',
    wait: { kind: 'screen', screen: 'lock_setup' },
    prompt: 'Tap Configure wallet lock',
  },
  {
    id: 'lock-setup',
    screen: 'lock_setup',
    target: '.lock-setup-screen',
    title: 'PIN or combo',
    body: 'Choose a PIN or a sequence of the shell buttons, and enter it twice. You can have it lock whenever you leave the app, and pick how long it waits before locking. Too many wrong tries wait out a cooldown. In practice, saving is switched off.',
  },
  {
    id: 'ring',
    screen: 'settings',
    target: '[aria-labelledby="nfc-section-title"]',
    title: 'Ring backup',
    body: 'An NFC ring can carry your backup. If you lose this phone, the ring brings your wallet back on a new one.',
  },
  {
    id: 'nfc-backup',
    screen: 'nfc_recovery',
    target: '.nfc-recovery-screen',
    title: 'Backing up to a ring',
    body: 'Manage backup shows whether your backup is on, writes your recovery capsule to the ring, and rebuilds it when your wallet changes. Turning it on shows a recovery phrase to write down. In practice, all of it is switched off.',
  },
  {
    id: 'nfc-recover',
    screen: 'recovery',
    target: '.recovery-screen',
    title: 'Getting it back',
    body: 'Inspect or recover reads a ring and, with your recovery phrase, checks what it holds. On a new phone, that brings your wallet back.',
  },
  {
    id: 'replay',
    screen: 'settings',
    target: '[data-tour="tutorial-button"]',
    title: 'Come back any time',
    body: 'You can replay this tour from here whenever you like.',
  },
  {
    id: 'done',
    screen: 'home',
    target: '.dsm-menu-item[data-label="WALLET"]',
    title: "You're ready",
    body: 'That is everything. Your real wallet is back, exactly as you left it. Press B to back out of any screen, and look for i whenever you want an explanation.',
  },
];
