// SPDX-License-Identifier: MIT OR Apache-2.0

//! DSM namespace tags: misc

mod addressing;
mod protocol;
mod testing;
mod token_ops;

pub use addressing::*;
pub use protocol::*;
pub use testing::*;
pub use token_ops::*;

#[cfg(test)]
pub(super) const TAGS: &[&str] = &[
    TAG_DSM_ADDR_D,
    TAG_DSM_ADDR_G,
    TAG_DSM_ADDR_T,
    TAG_DSM_ANCHOR_TICK,
    TAG_DSM_BALANCE_ANCHOR,
    TAG_DSM_BTC_DEPOSIT_ID,
    TAG_DSM_BTC_KEY_ENC,
    TAG_DSM_CANONICAL_BALANCE,
    TAG_DSM_CANONICAL_LP,
    TAG_DSM_CONTACT_ADD,
    TAG_DSM_COUNTERPARTY_ID,
    TAG_DSM_DETERMINISTIC_ID,
    TAG_DSM_DETERMINISTIC_TIME,
    TAG_DSM_DEV_ENT_V2,
    TAG_DSM_DJTE_SHARD_MERKLE,
    TAG_DSM_EXTERNAL_EVIDENCE,
    TAG_DSM_EXTERNAL_SOURCE_ID,
    TAG_DSM_FAUCET_CLAIM,
    TAG_DSM_MOMENT,
    TAG_DSM_MOMENT_NODE,
    TAG_DSM_OP_VERIFY,
    TAG_DSM_PRE_FINALIZATION,
    TAG_DSM_PROOF_ROOT,
    TAG_DSM_PROTOCOL_TRANSITION,
    TAG_DSM_RECEIPT,
    TAG_DSM_RECEIPT_BIND_SESSION,
    TAG_DSM_SILICON_FP_V4,
    TAG_DSM_SMT_PROOF,
    TAG_DSM_SPARSE_IDX,
    TAG_DSM_STATE_ENTROPY,
    TAG_DSM_SYSTEM_OWNER,
    TAG_DSM_TOKEN_FACTORY,
    TAG_DSM_TOKEN_ID,
    TAG_DSM_TOKEN_METADATA,
    TAG_DSM_TOKEN_MPC_PARTICIPANT,
    TAG_DSM_TOKEN_OP,
    TAG_DSM_TRANSITION,
    TAG_DSM_WAL_KEY_CTX,
];
