// SPDX-License-Identifier: MIT OR Apache-2.0

//! DSM namespace tags: misc

// TAGS below is consumed only by the cfg(test) `all_tags()` collector, so
// both it and this import are test-only in a non-test build.
#[cfg(test)]
use crate::crypto::domain::TaggedHashDomain;

mod addressing;
mod economic;
mod protocol;
mod testing;
mod token_ops;

pub use addressing::*;
pub use economic::*;
pub use protocol::*;
pub use testing::*;
pub use token_ops::*;

#[cfg(test)]
#[cfg(test)]
pub(super) const TAGS: &[TaggedHashDomain<'static>] = &[
    TAG_DSM_ADDR_D,
    TAG_DSM_ADDR_G,
    TAG_DSM_ADDR_T,
    TAG_DSM_ANCHOR_TICK,
    TAG_DSM_BALANCE_ANCHOR,
    TAG_DSM_BTC_DEPOSIT_ID,
    TAG_DSM_BTC_KEY_ENC,
    TAG_DSM_CANONICAL_BALANCE,
    TAG_DSM_CANONICAL_LP,
    TAG_DSM_CONTACT_ADD,
    TAG_DSM_COUNTERPARTY_ID,
    TAG_DSM_DETERMINISTIC_ID,
    TAG_DSM_DETERMINISTIC_TIME,
    TAG_DSM_DEV_ENT_V2,
    TAG_DSM_DJTE_SHARD_MERKLE,
    TAG_DSM_ECONOMIC_ADMISSION_MANIFEST,
    TAG_DSM_ECONOMIC_BALANCE_KEY,
    TAG_DSM_ECONOMIC_CONSUMED_SOURCE_KEY,
    TAG_DSM_ECONOMIC_LEAF_STATE,
    TAG_DSM_ECONOMIC_DSM_SUBSTRATE_OBJ,
    TAG_DSM_ECONOMIC_AUTHORITY_EVIDENCE,
    TAG_DSM_ECONOMIC_SUCCESSOR_EVIDENCE,
    TAG_DSM_EK_CERT_STEP,
    TAG_DSM_PEER_TRANSFER_ACCEPTANCE,
    TAG_DSM_RECIPIENT_ECONOMIC_RELEASE,
    TAG_DSM_RECIPIENT_ECONOMIC_RELEASE_SIGN,
    TAG_DSM_ECONOMIC_SUBSTRATE_SIGN,
    TAG_DSM_ECONOMIC_ROOT_CLAIM_ENVELOPE,
    TAG_DSM_ECONOMIC_ROOT_CLAIM_SIGN,
    TAG_DSM_ECONOMIC_SETTLEMENT_RECEIPT_KEY,
    TAG_DSM_ECONOMIC_SMT_LEAF,
    TAG_DSM_ECONOMIC_SMT_NODE,
    TAG_DSM_ECONOMIC_TRANSITION_WITNESS_OBJ,
    TAG_DSM_ECONOMIC_VAULT_RESERVE_KEY,
    TAG_DSM_ECONOMIC_OPERATION_DIGEST_DSM,
    TAG_DSM_ECONOMIC_OPERATION_ID_DSM,
    TAG_DSM_ECON_SOURCE_ERA_FAUCET_TICKET,
    TAG_DSM_ECON_SOURCE_SAME_TRANSITION_MOVE,
    TAG_DSM_ERA_FAUCET_ID,
    TAG_DSM_ERA_FAUCET_TICKET_CLAIM,
    TAG_DSM_ERA_FAUCET_TICKET_CLAIM_SIGN,
    TAG_DSM_ERA_FAUCET_TICKET_SELECT,
    TAG_DSM_ECON_SOURCE_VALIDATED_PEER_DEBIT,
    TAG_DSM_TRADER_ECONOMIC_ROOT_REGISTER_KEY,
    TAG_DSM_DLV_CLOSE_COMMIT,
    TAG_DSM_DLV_CLOSE_X,
    TAG_DSM_EXTERNAL_EVIDENCE,
    TAG_DSM_EXTERNAL_SOURCE_ID,
    TAG_DSM_FAUCET_CLAIM,
    TAG_DSM_FROZEN_ARTIFACT_V1,
    TAG_DSM_MOMENT,
    TAG_DSM_MOMENT_NODE,
    TAG_DSM_OP_VERIFY,
    TAG_DSM_PRE_FINALIZATION,
    TAG_DSM_PROOF_ROOT,
    TAG_DSM_PROTOCOL_TRANSITION,
    TAG_DSM_RECEIPT,
    TAG_DSM_RECEIPT_BIND_SESSION,
    TAG_DSM_RECEIPT_B_CANONICAL,
    TAG_DSM_RECEIPT_EVIDENCE_A,
    TAG_DSM_RECEIPT_EVIDENCE_B,
    TAG_DSM_RELATIONSHIP_FINALIZED,
    TAG_DSM_RELATIONSHIP_FINALIZED_ARTIFACT,
    TAG_DSM_SETTLEMENT_SLOT_CLAIM_ENVELOPE_V2,
    TAG_DSM_SETTLEMENT_SLOT_CLAIM_V2,
    TAG_DSM_SILICON_FP_V4,
    TAG_DSM_SMT_PROOF,
    TAG_DSM_SPARSE_IDX,
    TAG_DSM_STATE_ENTROPY,
    TAG_DSM_ANCHOR_PRESENTATION_V1,
    TAG_DSM_STORAGE_SET,
    TAG_DSM_VAULT_STATE,
    TAG_DSM_DEVTREE_DELEGATION,
    TAG_DSM_DEVTREE_DELEGATION_GENESIS_SENTINEL_V1,
    TAG_DSM_DEVTREE_DELEGATION_SIGN,
    TAG_DSM_DEVTREE_TRANSITION,
    TAG_DSM_DEVTREE_TRANSITION_GENESIS_SENTINEL_V1,
    TAG_DSM_DEVTREE_TRANSITION_SIGN,
    TAG_DSM_STORAGE_OBJECT,
    TAG_DSM_VAULT_STATE_ANCHOR_V2,
    TAG_DSM_VAULT_STATE_ANCHOR_V3,
    TAG_DSM_VAULT_STATE_PARENT_GENESIS_V2,
    TAG_DSM_SYSTEM_OWNER,
    TAG_DSM_TOKEN_FACTORY,
    TAG_DSM_TOKEN_ID,
    TAG_DSM_TOKEN_METADATA,
    TAG_DSM_TOKEN_MPC_PARTICIPANT,
    TAG_DSM_TOKEN_OP,
    TAG_DSM_TRANSITION,
    TAG_DSM_WAL_KEY_CTX,
];
