-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dsm_sphincs]: function definitions
import Aeneas
import DsmSphincs.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace DSMSphincsRust

/-- [dsm_sphincs::next_layer]:
    Source: 'crates/dsm-sphincs/src/lib.rs', lines 547:0-549:1 -/
def next_layer
  (p : Params) (tree : Std.U64) : Result (Std.U32 × Std.U64) := do
  let i ← 1#u64 <<< p.hp
  let i1 ← i - 1#u64
  let i2 ← lift (tree &&& i1)
  let i3 ← lift (UScalar.cast .U32 i2)
  let i4 ← tree >>> p.hp
  ok (i3, i4)

end DSMSphincsRust
