-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dsm_sphincs]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace DSMSphincsRust

/-- [dsm_sphincs::Params]
    Source: 'crates/dsm-sphincs/src/lib.rs', lines 98:0-120:1 -/
structure Params where
  n : Std.Usize
  h : Std.Usize
  d : Std.Usize
  hp : Std.Usize
  a : Std.Usize
  k : Std.Usize
  len1 : Std.Usize
  len2 : Std.Usize
  len : Std.Usize
  md_bytes : Std.Usize
  tree_bytes : Std.Usize
  leaf_bytes : Std.Usize
  m : Std.Usize
  pk_bytes : Std.Usize
  sk_bytes : Std.Usize
  sig_bytes : Std.Usize

end DSMSphincsRust
